### ISSUE TITLE
Example for "amplification attack alone"?

### ISSUE THREAD

**Issue by boaks** [EricssonResearch/coap-actuators#19]
> An amplification attack alone can be a denial-of-service attack on a CoAP server by making it send a large amount of data. 

Really? 
Sorry, any server for any protocol must protect it self from overloading. Using that example would convert any HTTP server in a "victim". There we send 1k to read pictures of 200k.

**Comment by emanjon** [comment]
Please continue discussion at 
https://github.com/t2trg/t2trg-amplification-attacks/issues/5

(Due to lack of owner rights I could not transfer this repository and instead had to make a new one, I will manually create new issues there for any open issues).
