### ISSUE TITLE
Creating resources

### ISSUE THREAD

**Issue by boaks** [EricssonResearch/coap-actuators#20]
> An attacker can also increase or control the amplification factor by creating or updating resources. By creating new resources, an attacker can increase the size of /.well-known/core.

For me this requires to mention, that the server must support that "PUT/POST" and doesn't limit it.
It should also be mentioned, that usually the coap payload for one message is limited by 1024 or 1280.
So "An attacker may be able to increase ..., if the server doesn't limit that".

**Comment by emanjon** [comment]
Please continue discussion at 
https://github.com/t2trg/t2trg-amplification-attacks/issues/4

(Due to lack of owner rights I could not transfer this repository and instead had to make a new one, I will manually create new issues there for any open issues).
