### ISSUE TITLE
Adding proposals for mitigation?

### ISSUE THREAD

**Issue by boaks** [EricssonResearch/coap-actuators#23]
I would welcome, if proposals for mitigations are added.

E.g.:
Observe-Notify: send the first response/notify as separate CON message.

**Comment by emanjon** [comment]
Please continue discussion at 
https://github.com/t2trg/t2trg-amplification-attacks/issues/1

(Due to lack of owner rights I could not transfer this repository and instead had to make a new one, I will manually create new issues there for any open issues).
