### ISSUE TITLE
Scope of RFC6347? (Or better refer to RFC7252?)

### ISSUE THREAD

**Issue by boaks** [EricssonResearch/coap-actuators#5]
> The use of CoAP over UDP and DTLS is specified in {{RFC6347}}

RFC6347 doesn't mention CoAP.
RFC7252 instead includes advice when using (plain) UDP or DTLS.
So, I guess, the intended reference is RFC 7252.

**Comment by emanjon** [comment]
Yes, will be fixed in -01

**Comment by emanjon** [comment]
Fixed in the master branch.
