### ISSUE TITLE
freshness vs. replay protection

### ISSUE THREAD

**Issue by chrysn** [EricssonResearch/coap-actuators#8]
From the Ben Kaduk's comments on ERT:

> I think it would also be enlightening to have a comparison between the
> anti-replay/freshness properties provided by the optional DTLS replay
> protection mechanism and the Echo option.  I know they have differences,
> but I think there is also some commonality, and giving readers guidance
> on whether one vs the other suffices or both are needed could be useful.

I've given it a try but that would have needed more coap-attacks imports than practical; can we add a subsection on freshness-vs-replay here?

**Comment by boaks** [comment]
In my opinion, especially the combination of both provides some missing protection for "corner cases", e.g. using [draft-ietf-tls-dtls-connection-id](https://github.com/tlswg/dtls-conn-id/blob/master/draft-ietf-tls-dtls-connection-id.md#peer-address-update-peer-address-update).

**Comment by boaks** [comment]
Is it possible to get a link to the original message? I tried to search for that in the [core-mailing-list](https://mailarchive.ietf.org/arch/browse/core/) and the [issues of  echo-request-tag](https://github.com/core-wg/echo-request-tag/issues) but couldn't find it.

**Comment by emanjon** [comment]
https://datatracker.ietf.org/doc/draft-ietf-core-echo-request-tag/ballot/

**Comment by kaduk** [comment]
Also available at https://datatracker.ietf.org/doc/draft-ietf-core-echo-request-tag/history/ (though a bit more work to pull out), since the content at https://datatracker.ietf.org/doc/draft-ietf-core-echo-request-tag/ballot/ is going to change shortly.

**Comment by emanjon** [comment]
From a theoretical perspective I think they are completely different. I think the similarities comes from the use of sequence numbers in most (but not all) replay protections mechanisms. Sequence numbers can be used by the server as a relative measure of when a message was sent on a timescale of the sender.

Suggest to add the following text to the introduction:

"Freshness is a measure of when a message was sent on a timescale of the
recipient. A server that receives a request can either verify that the
request is fresh or determine that it cannot be verified that the request
is fresh.  What is considered a fresh is application dependent. Freshness
is completely different from replay protection, but most replay protection
mechanism use a sequence number. Assuming the client is well-behaving, such
a sequence numner that can be used by the server as a relative measure of
when a message was sent on a timescale of the sender."

Maybe the body also need more discussion on replay protection, I will have that in mind while I address Carsten's comments.

**Comment by emanjon** [comment]
I also added some text on how different protocols use sequence numners

```
Replay protection is
mandatory in TLS and OSCORE and optional in DTLS.  DTLS and TLS 
use sequence numbers for both requests and responses. In TLS the
sequence numbers are implicit and not sent in the record.
OSCORE use sequence numbers only for requests and some responses.
Most OSCORE responses are bound to the request and therefore,
enable the client to determine if the response is fresh or not.
```
